// Generated by CoffeeScript 1.7.1
(function() {
  var Local, read, receiveCallbacks, receiveRedirector, tcp, tcpServer;

  tcpServer = chrome.sockets.tcpServer;

  tcp = chrome.sockets.tcp;

  receiveCallbacks = {};

  read = function(sockId, callback) {
    receiveCallbacks[sockId] = callback;
    return tcp.setPaused(sockId, false);
  };

  receiveRedirector = function(info) {
    console.log('receiveRedirector', info);
    return receiveCallbacks[info.socketId](info.data);
  };

  tcp.onReceive.addListener(receiveRedirector);

  Local = (function() {
    function Local(config) {
      var BUF_SIZE, KEY, METHOD, PORT, REMOTE_PORT, SERVER, string2ArrayBuffer, that;
      SERVER = config.server;
      REMOTE_PORT = +config.server_port;
      PORT = +config.local_port;
      KEY = config.password;
      METHOD = config.method;
      BUF_SIZE = 1500;
      that = this;
      string2ArrayBuffer = function(string) {
        var arr, buf, i, _i, _ref;
        buf = new ArrayBuffer(string.length);
        arr = new Uint8Array(buf, 0, string.length);
        for (i = _i = 0, _ref = string.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
          arr[i] = string.charCodeAt(i);
        }
        return buf;
      };
      tcpServer.create({}, function(socketInfo) {
        var address, listen, port;
        that.listen = socketInfo.socketId;
        listen = that.listen;
        console.log("listen: " + listen);
        address = '0.0.0.0';
        port = PORT;
        chrome.runtime.onSuspend.addListener(function() {
          console.log('closing listen socket');
          return chrome.tcpServer.close(listen);
        });
        return tcpServer.listen(listen, address, port, function(result) {
          console.log('listen');
          console.assert(0 === result);
          return tcpServer.getInfo(listen, function(info) {
            var accept;
            console.log('server listening on localhost:' + info.localPort);
            accept = function(acceptInfo) {
              var encryptor, local;
              console.log('accepted');
              if (acceptInfo.clientSocketId === 0) {
                return;
              }
              local = acceptInfo.clientSocketId;
              console.log("accept " + local);
              encryptor = new Encryptor(KEY, METHOD);
              return tcp.create({}, function(socketInfo) {
                var remote;
                remote = socketInfo.socketId;
                return tcp.connect(remote, SERVER, REMOTE_PORT, function(result) {
                  console.log("connect " + remote);
                  if (result !== 0) {
                    console.log("close " + local + " " + remote);
                    tcp.close(local);
                    tcp.close(remote);
                    return;
                  }
                  console.assert(0 === result);
                  return read(local, function(data) {
                    return tcp.send(local, string2ArrayBuffer('\x05\x00'), function(readInfo) {
                      console.assert(readInfo.bytesSent === 2);
                      return read(local, function(data) {
                        console.assert(readInfo.resultCode > 0);
                        return tcp.send(local, string2ArrayBuffer('\x05\x00\x00\x01\x00\x00\x00\x00\x00\x00'), function(readInfo) {
                          var localToRemote, remoteToLocal;
                          console.assert(readInfo.bytesSent === 10);
                          localToRemote = function(data) {
                            console.assert(readInfo.resultCode > 0);
                            data = encryptor.encrypt(data);
                            return tcp.send(remote, data, function(readInfo) {
                              if (readInfo.bytesSent <= 0) {
                                console.log("close " + local + " " + remote);
                                tcp.close(local);
                                tcp.close(remote);
                                return;
                              }
                              console.assert(readInfo.bytesSent === data.byteLength);
                              return read(local, BUF_SIZE, localToRemote);
                            });
                          };
                          remoteToLocal = function(data) {
                            console.assert(readInfo.resultCode > 0);
                            data = encryptor.decrypt(data);
                            return tcp.send(local, data, function(readInfo) {
                              if (readInfo.bytesSent <= 0) {
                                console.log("close " + local + " " + remote);
                                tcp.close(local);
                                tcp.close(remote);
                                return;
                              }
                              console.assert(readInfo.bytesSent === data.byteLength);
                              return read(remote, BUF_SIZE, remoteToLocal);
                            });
                          };
                          read(local, localToRemote);
                          return read(remote, remoteToLocal);
                        });
                      });
                    });
                  });
                });
              });
            };
            return tcpServer.onAccept.addListener(accept);
          });
        });
      });
    }

    Local.prototype.close = function() {
      console.log(this.listen);
      if (this.listen) {
        return tcpServer.close(this.listen);
      }
    };

    return Local;

  })();

  window.Local = Local;

}).call(this);
